# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkArchitectureMVCDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher','3.6.1'
pod 'RxSwift', '~> 3.4.0'
pod 'Moya', '~> 8.0.3'
pod 'Moya/RxSwift', '~> 8.0.3'
pod 'ObjectMapper', '~> 2.2.5'
pod 'AwesomeCache', '~> 5.0'

  # Pods for NetworkArchitectureMVCDemo

  target 'NetworkArchitectureMVCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkArchitectureMVCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
