# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkArchitectureMVCDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Kingfisher', '~> 4.2.0'
pod 'RxSwift', '~> 4.0.0'
pod 'Moya', '~> 10.0.0'
pod 'Moya/RxSwift', '~> 10.0.0'
pod 'ObjectMapper', '~> 3.1.0'
pod 'AwesomeCache', '~> 5.0'

  # Pods for NetworkArchitectureMVCDemo

  target 'NetworkArchitectureMVCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkArchitectureMVCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
